import type { Product, Category, Order } from './types';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => {
    const img = PlaceHolderImages.find(p => p.id === id);
    if (!img) return { url: 'https://placehold.co/800x600', hint: 'placeholder' };
    return { url: img.imageUrl, hint: img.imageHint };
}

export const categories: Category[] = [
    { id: 'beds', name: 'Beds', image: findImage('category-beds').url, imageHint: findImage('category-beds').hint },
    { id: 'sofas', name: 'Sofas', image: findImage('category-sofas').url, imageHint: findImage('category-sofas').hint },
    { id: 'chairs', name: 'Chairs', image: findImage('category-chairs').url, imageHint: findImage('category-chairs').hint },
    { id: 'tables', name: 'Tables', image: findImage('category-tables').url, imageHint: findImage('category-tables').hint },
    { id: 'office-furniture', name: 'Office Furniture', image: findImage('category-office').url, imageHint: findImage('category-office').hint },
    { id: 'cabinets', name: 'Cabinets', image: findImage('category-cabinets').url, imageHint: findImage('category-cabinets').hint },
];

export const products: Product[] = [
    {
        id: '1',
        name: 'Zanzibar Serenity Bed',
        description: 'Experience tranquility with this masterfully crafted bed, made from local Mninga wood. Its elegant design and sturdy construction promise restful nights and a beautiful bedroom centerpiece.',
        price: 1200000,
        category: 'beds',
        images: [findImage('prod-1-img-1'), findImage('prod-1-img-2')],
        sizes: ['Queen', 'King'],
        materials: ['Mninga Wood', 'Linen Upholstery'],
        stock: 15,
        isFeatured: true,
        createdAt: new Date('2023-10-01'),
    },
    {
        id: '2',
        name: 'Spice Isle Sofa',
        description: 'A plush and inviting sofa that captures the warmth of Zanzibar. Perfect for family gatherings, its comfortable cushions and durable fabric make it a living room essential.',
        price: 2500000,
        category: 'sofas',
        images: [findImage('prod-2-img-1'), findImage('prod-2-img-2')],
        materials: ['Eucalyptus Frame', 'High-Density Foam', 'Cotton Blend Fabric'],
        stock: 8,
        isFeatured: true,
        createdAt: new Date('2023-10-05'),
    },
    {
        id: '3',
        name: 'Swahili Coast Chair',
        description: 'An elegant armchair featuring traditional Swahili carvings and a comfortable, modern design. A perfect accent piece for any room.',
        price: 450000,
        category: 'chairs',
        images: [findImage('prod-3-img-1'), findImage('prod-15-img-1')],
        materials: ['Mango Wood', 'Woven Rattan'],
        stock: 25,
        isFeatured: false,
        createdAt: new Date('2023-10-10'),
    },
    {
        id: '4',
        name: 'Forodhani Dining Table',
        description: 'Gather your loved ones around this spacious and robust dining table. Made from reclaimed Dhow wood, each table tells a unique story of the sea.',
        price: 1800000,
        category: 'tables',
        images: [findImage('prod-4-img-1'), findImage('prod-13-img-1')],
        sizes: ['6-Seater', '8-Seater'],
        materials: ['Reclaimed Dhow Wood', 'Steel'],
        stock: 12,
        isFeatured: true,
        createdAt: new Date('2023-09-15'),
    },
    {
        id: '5',
        name: 'Sultan\'s Cabinet',
        description: 'A majestic cabinet with intricate brass inlays and ample storage. This piece adds a touch of royal elegance to your living or dining space.',
        price: 2200000,
        category: 'cabinets',
        images: [findImage('prod-5-img-1')],
        materials: ['Mvule Wood', 'Brass'],
        stock: 7,
        isFeatured: false,
        createdAt: new Date('2023-09-20'),
    },
    {
        id: '6',
        name: 'Nungwi Wardrobe',
        description: 'A spacious and stylish wardrobe with a clean, modern aesthetic. Features double doors, a hanging rail, and multiple shelves for optimal organization.',
        price: 2800000,
        category: 'wardrobes',
        images: [findImage('prod-6-img-1')],
        materials: ['Engineered Wood', 'Matte Finish Laminate'],
        stock: 10,
        isFeatured: false,
        createdAt: new Date('2023-11-01'),
    },
    {
        id: '7',
        name: 'Stone Town Executive Desk',
        description: 'Command your workspace with this premium executive desk. It offers a large surface area, multiple drawers, and a timeless design that means business.',
        price: 1500000,
        category: 'office-furniture',
        images: [findImage('prod-7-img-1')],
        materials: ['Mahogany Wood', 'Leatherette Top'],
        stock: 18,
        isFeatured: true,
        createdAt: new Date('2023-11-05'),
    },
    {
        id: '8',
        name: 'Paje Loveseat',
        description: 'A cozy and chic two-seater sofa, perfect for smaller spaces or as a complement to a larger set. Its vibrant color options bring life to any room.',
        price: 1350000,
        category: 'sofas',
        images: [findImage('prod-8-img-1')],
        materials: ['Pine Wood Frame', 'Velvet Fabric'],
        stock: 15,
        isFeatured: false,
        createdAt: new Date('2023-11-12'),
    },
    {
        id: '9',
        name: 'Mtoni Accent Chair',
        description: 'A bold and beautiful accent chair that makes a statement. With its unique silhouette and comfortable padding, it\'s both a seat and a piece of art.',
        price: 600000,
        category: 'chairs',
        images: [findImage('prod-9-img-1')],
        materials: ['Metal Frame', 'Bouclé Fabric'],
        stock: 20,
        isFeatured: true,
        createdAt: new Date('2023-11-18'),
    },
    {
        id: '10',
        name: 'Kendwa Coffee Table',
        description: 'A minimalist coffee table with a rustic touch. The solid wood top and sleek metal legs provide a perfect balance of nature and industry.',
        price: 750000,
        category: 'tables',
        images: [findImage('prod-10-img-1')],
        materials: ['Acacia Wood', 'Powder-Coated Steel'],
        stock: 22,
        isFeatured: false,
        createdAt: new Date('2023-10-25'),
    },
    {
        id: '11',
        name: 'Pemba Bookshelf',
        description: 'An open and airy bookshelf to display your favorite books and decor. Its asymmetrical design adds a modern, dynamic element to your space.',
        price: 950000,
        category: 'cabinets',
        images: [findImage('prod-11-img-1')],
        materials: ['Oak Wood Veneer', 'Metal Frame'],
        stock: 14,
        isFeatured: false,
        createdAt: new Date('2023-10-28'),
    },
    {
        id: '12',
        name: 'Kiwengwa King Bed',
        description: 'A grand and luxurious king-sized bed with a tall, tufted headboard. This bed is designed to be the ultimate sanctuary for rest and relaxation.',
        price: 1600000,
        category: 'beds',
        images: [findImage('prod-12-img-1')],
        sizes: ['King'],
        materials: ['Hardwood Frame', 'Plush Velvet'],
        stock: 9,
        isFeatured: false,
        createdAt: new Date('2023-11-20'),
    },
    {
        id: '14',
        name: 'Ergonomic Office Chair',
        description: 'Stay comfortable and productive with this fully adjustable ergonomic office chair. Features lumbar support, adjustable armrests, and a breathable mesh back.',
        price: 850000,
        category: 'office-furniture',
        images: [findImage('prod-14-img-1')],
        materials: ['Nylon Mesh', 'High-Density Foam', 'Steel Base'],
        stock: 30,
        isFeatured: false,
        createdAt: new Date('2023-11-25'),
    }
];

export const orders: Order[] = [
    {
      id: 'ORD001',
      customerName: 'Asha Juma',
      phone: '0777 123 456',
      address: 'Michenzani, Zanzibar',
      items: [
        { product: products[1], quantity: 1 },
        { product: products[8], quantity: 2 },
      ],
      total: products[1].price * 1 + products[8].price * 2,
      status: 'Delivered',
      createdAt: new Date('2024-05-20T10:30:00Z'),
    },
    {
      id: 'ORD002',
      customerName: 'Fatma Ali',
      phone: '0655 987 654',
      address: 'Kijangwani, Zanzibar',
      items: [{ product: products[3], quantity: 1 }],
      total: products[3].price * 1,
      status: 'Processing',
      createdAt: new Date('2024-05-22T14:00:00Z'),
    },
    {
      id: 'ORD003',
      customerName: 'John Smith',
      phone: '0788 555 111',
      address: 'Nungwi, Zanzibar',
      items: [{ product: products[6], quantity: 1 }],
      total: products[6].price * 1,
      status: 'Pending',
      createdAt: new Date('2024-05-23T09:15:00Z'),
    },
    {
        id: 'ORD004',
        customerName: 'Siti Mohamed',
        phone: '0712 345 678',
        address: 'Bububu, Zanzibar',
        items: [
            { product: products[0], quantity: 1 },
            { product: products[9], quantity: 1 },
        ],
        total: products[0].price + products[9].price,
        status: 'Delivered',
        createdAt: new Date('2024-05-18T11:45:00Z'),
    },
    {
        id: 'ORD005',
        customerName: 'David Ochieng',
        phone: '0689 112 233',
        address: 'Paje, Zanzibar',
        items: [{ product: products[2], quantity: 4 }],
        total: products[2].price * 4,
        status: 'Cancelled',
        createdAt: new Date('2024-05-19T16:20:00Z'),
    },
  ];

export const getProducts = () => products;
export const getProductById = (id: string) => products.find(p => p.id === id);
export const getCategories = () => categories;
export const getCategoryById = (id: string) => categories.find(c => c.id === id);
export const getOrders = () => orders;
export const getOrderById = (id: string) => orders.find(o => o.id === id);
